# yaml-language-server: $schema=https://raw.githubusercontent.com/yurifyodorov/tcms-content-schema/main/schemas/project.schema.json

id: "{cuid}"
title: "Test project"
description: |
  ## Project the best
  - 1
  - 2 
  - [3](https://google.com)
cases:
  - "case-1"